#!/bin/bash
NPROC=$(grep -c ^processor /proc/cpuinfo 2>/dev/null || 1) \
&& apk add  --no-cache --virtual .php-build-deps \
  $PHPIZE_DEPS \
  curl-dev \
  imagemagick-dev \
  libtool \
  libxml2-dev \
  sqlite-dev \
  freetype-dev \
  libjpeg-turbo-dev \
  libpng-dev \
  libmemcached-dev \
  zlib-dev \
  cyrus-sasl-dev \
  gmp-dev \
  libmcrypt-dev \
\
&& apk add --no-cache \
  libmcrypt \
  libltdl \
  curl \
  imagemagick \
  freetype \
  libpng \
  libjpeg-turbo \
  libmemcached-libs \
  zlib \
\
&& pecl install imagick \
&& pecl install redis \
&& pecl install memcached \
&& docker-php-ext-enable redis imagick memcached \
\
&& docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
&& docker-php-ext-configure gmp \
&& docker-php-ext-configure mcrypt \
&& docker-php-ext-install -j${NPROC} \
  mcrypt \
  iconv \
  curl \
  mbstring \
  pdo \
  pdo_mysql \
  pdo_sqlite \
  mysqli \
  pcntl \
  tokenizer \
  xml \
  zip \
  soap \
  gd \
  gmp \
  bcmath \
\
&& curl -s https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin/ --filename=composer \
&& chmod +x /usr/local/bin/composer \
&& echo 'export PATH=/xooxx/.composer/vendor/bin:$PATH' >>/etc/profile \
&& echo "memory_limit = 2G;" > /usr/local/etc/php/php.ini \
\
&& apk del -f .php-build-deps
